#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXxf86vm
Version  : 1.1.4
Release  : 7
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXxf86vm-1.1.4.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXxf86vm-1.1.4.tar.gz
Summary  : XFree86 Video Mode Extension Library
Group    : Development/Tools
License  : MIT
Requires: libXxf86vm-lib
Requires: libXxf86vm-doc
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xf86vidmodeproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
libXxf86vm - Extension library for the XFree86-VidMode X extension
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXxf86vm package.
Group: Development
Requires: libXxf86vm-lib
Provides: libXxf86vm-devel

%description dev
dev components for the libXxf86vm package.


%package doc
Summary: doc components for the libXxf86vm package.
Group: Documentation

%description doc
doc components for the libXxf86vm package.


%package lib
Summary: lib components for the libXxf86vm package.
Group: Libraries

%description lib
lib components for the libXxf86vm package.


%prep
%setup -q -n libXxf86vm-1.1.4

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/xf86vmode.h
/usr/lib64/libXxf86vm.so
/usr/lib64/pkgconfig/xxf86vm.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXxf86vm.so.1
/usr/lib64/libXxf86vm.so.1.0.0
